In [2]:
import numpy as np

# Creating Numpy Arrays from Python Lists

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
np.array([3,1, 2,3,1], dtype='float32')

array([3., 1., 2., 3., 1.], dtype=float32)

In [8]:
a1 = np.array([1,2,3,4,5])

In [9]:
type(a1)

numpy.ndarray

In [12]:
a2 = np.array([[1,2,3,4],
                [4,5,6,7]]) 

In [13]:
a2.shape

(2, 4)

In [14]:
a2.ndim

2

In [15]:
a2.dtype

dtype('int32')

In [16]:
a2.size

8

## Creating Numpy Arrays from Scratch

### `Zeros`, `ones`, `full`, `arange`, `linspace`

In [24]:
np.zeros([2,4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.ones([3,5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
np.full((3,5),6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [4]:
np.linspace(0,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

##  `random`

In [22]:
# seed for repeoducibility
np.random.seed(0)

np.random.random((4,4))


array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [10]:
np.random.random((4,4))

array([[0.82718579, 0.04830106, 0.07938747, 0.99587511],
       [0.42724417, 0.53224791, 0.53864745, 0.87755223],
       [0.37659848, 0.46881581, 0.9391112 , 0.64934879],
       [0.56267741, 0.45867943, 0.16256484, 0.70486575]])

In [24]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [26]:
np.random.randint(0, 10, (4,5))

array([[2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1],
       [4, 9, 8, 1, 1],
       [7, 9, 9, 3, 6]])